logging:
  level:
    io.mustelidae.grantotter: info
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.tool.schema: error
    com.zaxxer.hikari: error
    io.swagger.models.parameters.AbstractSerializableParameter: error

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 7300

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: grantotter
